CREATE TABLE USERS (
  USER_ID           char(6) NOT NULL, 
  USER_NAME         varchar(30) NOT NULL, 
  USER_PHONE_NUMBER char(14) DEFAULT '+8801XXXXXXXXX' NOT NULL UNIQUE, 
  USER_EMAIL        varchar(30) NOT NULL UNIQUE, 
  USER_ADDRESS      varchar(50) NOT NULL, 
  USER_CATEGORY     varchar(10) NOT NULL, 
  USER_PASSWORD     varchar(20) NOT NULL, 
  PRIMARY KEY (USER_ID));
CREATE TABLE REGION (
  REGION_ID   int(3) NOT NULL AUTO_INCREMENT, 
  REGION_NAME varchar(30) NOT NULL, 
  BROKER_ID   char(6) NOT NULL, 
  PRIMARY KEY (REGION_ID));
CREATE TABLE BROKER (
  BROKER_ID      char(6) NOT NULL, 
  BROKER_NAME    varchar(30) NOT NULL, 
  B_PASSWORD     varchar(20) NOT NULL, 
  B_EMAIL        varchar(30) NOT NULL UNIQUE, 
  B_PHONE_NUMBER char(14) DEFAULT '+8801XXXXXXXXX' NOT NULL UNIQUE, 
  B_ADDRESS      varchar(30) NOT NULL, 
  PRIMARY KEY (BROKER_ID));
CREATE TABLE HISTORY (
  HISTORY_ID   int(6) NOT NULL AUTO_INCREMENT, 
  HISTORY_DATE date DEFAULT '2019-08-04' NOT NULL, 
  USER_ID      char(6) NOT NULL, 
  BROKER_ID    char(6) NOT NULL, 
  DETAILS_ID   int(6) NOT NULL, 
  PRIMARY KEY (HISTORY_ID));
CREATE TABLE PLOT_DETAILS (
  DETAILS_ID int(6) NOT NULL AUTO_INCREMENT, 
  AREA       varchar(30) NOT NULL, 
  LAND_SPACE float NOT NULL, 
  LAND_PRICE int(10) NOT NULL, 
  RS_NUMBR   int(8) NOT NULL UNIQUE, 
  CS_NUMBR   int(8) NOT NULL UNIQUE, 
  L_STATUS   varchar(20) NOT NULL, 
  USER_ID    char(6) NOT NULL, 
  BROKER_ID  char(6) NOT NULL, 
  REGION_ID  int(3) NOT NULL, 
  PRIMARY KEY (DETAILS_ID));
CREATE TABLE MASSAGE (
  MASSAGE_ID   int(10) NOT NULL AUTO_INCREMENT, 
  MASSAGE_TIME time NOT NULL, 
  MASSAGE_DATE date NOT NULL, 
  MASSAGE      varchar(255) NOT NULL, 
  BROKER_ID    char(6) NOT NULL, 
  USER_ID      char(6) NOT NULL, 
  PRIMARY KEY (MASSAGE_ID));
CREATE TABLE USERS_REGION (
  USER_ID   char(6) NOT NULL, 
  REGION_ID int(3) NOT NULL, 
  PRIMARY KEY (USER_ID, 
  REGION_ID));
ALTER TABLE HISTORY ADD CONSTRAINT USER_HISTORY FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE HISTORY ADD CONSTRAINT BROKER_HISTORY FOREIGN KEY (BROKER_ID) REFERENCES BROKER (BROKER_ID);
ALTER TABLE HISTORY ADD CONSTRAINT DETAILS_HISTORY FOREIGN KEY (DETAILS_ID) REFERENCES PLOT_DETAILS (DETAILS_ID);
ALTER TABLE MASSAGE ADD CONSTRAINT BROKER_MSG FOREIGN KEY (BROKER_ID) REFERENCES BROKER (BROKER_ID);
ALTER TABLE MASSAGE ADD CONSTRAINT USER_MSG FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE REGION ADD CONSTRAINT BROKER_REGION FOREIGN KEY (BROKER_ID) REFERENCES BROKER (BROKER_ID);
ALTER TABLE USERS_REGION ADD CONSTRAINT FKUSERS_REGI259217 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE USERS_REGION ADD CONSTRAINT FKUSERS_REGI30530 FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID);
ALTER TABLE PLOT_DETAILS ADD CONSTRAINT USER_DETAILS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE PLOT_DETAILS ADD CONSTRAINT BROKER_DETAILS FOREIGN KEY (BROKER_ID) REFERENCES BROKER (BROKER_ID);
ALTER TABLE PLOT_DETAILS ADD CONSTRAINT REGION_DETAILS FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID);
ALTER TABLE region
ADD CONSTRAINT uq100 UNIQUE(BROKER_ID);
ALTER TABLE plot_details
DROP COLUMN RS_NUMBER;
ALTER TABLE plot_details
DROP COLUMN CS_NUMBR;
ALTER TABLE plot_details
ADD COLUMN CS_NUMBR int(5) NOT NULL;
ALTER TABLE plot_details
ADD COLUMN RS_NUMBR int(5) NOT NULL;
ALTER TABLE plot_details
ADD COLUMN CHECK_VALIDITI VARCHAR(7) DEFAULT 'INVALID';
ALTER TABLE plot_details
DROP COLUMN L_STATUS;
ALTER TABLE plot_details
ADD COLUMN L_STATUS VARCHAR(6) DEFAULT 'UNSOLD';
ALTER TABLE plot_details
DROP FOREIGN KEY BROKER_DETAILS
ALTER TABLE plot_details
DROP COLUMN BROKER_ID